weather = {
    "current_condition": [
        {
            "FeelsLikeC": "21",
            "FeelsLikeF": "70",
            "cloudcover": "100",
            "humidity": "100",
            "localObsDateTime": "2024-02-17 04:59 AM",
            "observation_time": "05:59 PM",
            "precipInches": "0.0",
            "precipMM": "0.0",
            "pressure": "1020",
            "pressureInches": "30",
            "temp_C": "21",
            "temp_F": "70",
            "uvIndex": "1",
            "visibility": "10",
            "visibilityMiles": "6",
            "weatherCode": "122",
            "weatherDesc": [{"value": "Overcast"}],
            "weatherIconUrl": [{"value": ""}],
            "winddir16Point": "N",
            "winddirDegree": "10",
            "windspeedKmph": "4",
            "windspeedMiles": "2",
        }
    ],
    "nearest_area": [
        {
            "areaName": [{"value": "Kirribilli"}],
            "country": [{"value": "Australia"}],
            "latitude": "-33.850",
            "longitude": "151.217",
            "population": "3483",
            "region": [{"value": "New South Wales"}],
            "weatherUrl": [{"value": ""}],
        }
    ],
    "request": [{"query": "Lat -33.85 and Lon 151.22", "type": "LatLon"}],
    "weather": [
        {
            "astronomy": [
                {
                    "moon_illumination": "54",
                    "moon_phase": "Waxing Gibbous",
                    "moonrise": "02:27 PM",
                    "moonset": "No moonset",
                    "sunrise": "06:31 AM",
                    "sunset": "07:47 PM",
                }
            ],
            "avgtempC": "23",
            "avgtempF": "74",
            "date": "2024-02-17",
            "hourly": [
                {
                    "DewPointC": "21",
                    "DewPointF": "70",
                    "FeelsLikeC": "25",
                    "FeelsLikeF": "77",
                    "HeatIndexC": "25",
                    "HeatIndexF": "77",
                    "WindChillC": "23",
                    "WindChillF": "73",
                    "WindGustKmph": "24",
                    "WindGustMiles": "15",
                    "chanceoffog": "0",
                    "chanceoffrost": "0",
                    "chanceofhightemp": "0",
                    "chanceofovercast": "0",
                    "chanceofrain": "0",
                    "chanceofremdry": "94",
                    "chanceofsnow": "0",
                    "chanceofsunshine": "94",
                    "chanceofthunder": "0",
                    "chanceofwindy": "0",
                    "cloudcover": "19",
                    "diffRad": "0.0",
                    "humidity": "91",
                    "precipInches": "0.0",
                    "precipMM": "0.0",
                    "pressure": "1021",
                    "pressureInches": "30",
                    "shortRad": "0.0",
                    "tempC": "23",
                    "tempF": "73",
                    "time": "0",
                    "uvIndex": "1",
                    "visibility": "10",
                    "visibilityMiles": "6",
                    "weatherCode": "113",
                    "weatherDesc": [{"value": "Clear "}],
                    "weatherIconUrl": [{"value": ""}],
                    "winddir16Point": "N",
                    "winddirDegree": "5",
                    "windspeedKmph": "15",
                    "windspeedMiles": "9",
                },
                {
                    "DewPointC": "20",
                    "DewPointF": "68",
                    "FeelsLikeC": "21",
                    "FeelsLikeF": "70",
                    "HeatIndexC": "24",
                    "HeatIndexF": "76",
                    "WindChillC": "21",
                    "WindChillF": "70",
                    "WindGustKmph": "11",
                    "WindGustMiles": "7",
                    "chanceoffog": "0",
                    "chanceoffrost": "0",
                    "chanceofhightemp": "0",
                    "chanceofovercast": "86",
                    "chanceofrain": "74",
                    "chanceofremdry": "0",
                    "chanceofsnow": "0",
                    "chanceofsunshine": "0",
                    "chanceofthunder": "0",
                    "chanceofwindy": "0",
                    "cloudcover": "87",
                    "diffRad": "0.0",
                    "humidity": "93",
                    "precipInches": "0.0",
                    "precipMM": "0.0",
                    "pressure": "1020",
                    "pressureInches": "30",
                    "shortRad": "0.0",
                    "tempC": "21",
                    "tempF": "70",
                    "time": "300",
                    "uvIndex": "1",
                    "visibility": "10",
                    "visibilityMiles": "6",
                    "weatherCode": "176",
                    "weatherDesc": [{"value": "Patchy rain nearby"}],
                    "weatherIconUrl": [{"value": ""}],
                    "winddir16Point": "NNW",
                    "winddirDegree": "345",
                    "windspeedKmph": "6",
                    "windspeedMiles": "4",
                },
                {
                    "DewPointC": "20",
                    "DewPointF": "68",
                    "FeelsLikeC": "21",
                    "FeelsLikeF": "70",
                    "HeatIndexC": "24",
                    "HeatIndexF": "76",
                    "WindChillC": "21",
                    "WindChillF": "70",
                    "WindGustKmph": "4",
                    "WindGustMiles": "2",
                    "chanceoffog": "0",
                    "chanceoffrost": "0",
                    "chanceofhightemp": "0",
                    "chanceofovercast": "33",
                    "chanceofrain": "0",
                    "chanceofremdry": "91",
                    "chanceofsnow": "0",
                    "chanceofsunshine": "89",
                    "chanceofthunder": "0",
                    "chanceofwindy": "0",
                    "cloudcover": "40",
                    "diffRad": "1.9",
                    "humidity": "93",
                    "precipInches": "0.0",
                    "precipMM": "0.0",
                    "pressure": "1021",
                    "pressureInches": "30",
                    "shortRad": "3.6",
                    "tempC": "21",
                    "tempF": "70",
                    "time": "600",
                    "uvIndex": "1",
                    "visibility": "10",
                    "visibilityMiles": "6",
                    "weatherCode": "116",
                    "weatherDesc": [{"value": "Partly Cloudy "}],
                    "weatherIconUrl": [{"value": ""}],
                    "winddir16Point": "NNE",
                    "winddirDegree": "21",
                    "windspeedKmph": "2",
                    "windspeedMiles": "1",
                },
                {
                    "DewPointC": "21",
                    "DewPointF": "69",
                    "FeelsLikeC": "26",
                    "FeelsLikeF": "79",
                    "HeatIndexC": "26",
                    "HeatIndexF": "79",
                    "WindChillC": "24",
                    "WindChillF": "76",
                    "WindGustKmph": "9",
                    "WindGustMiles": "6",
                    "chanceoffog": "0",
                    "chanceoffrost": "0",
                    "chanceofhightemp": "16",
                    "chanceofovercast": "0",
                    "chanceofrain": "0",
                    "chanceofremdry": "86",
                    "chanceofsnow": "0",
                    "chanceofsunshine": "90",
                    "chanceofthunder": "0",
                    "chanceofwindy": "0",
                    "cloudcover": "24",
                    "diffRad": "47.1",
                    "humidity": "79",
                    "precipInches": "0.0",
                    "precipMM": "0.0",
                    "pressure": "1021",
                    "pressureInches": "30",
                    "shortRad": "213.1",
                    "tempC": "24",
                    "tempF": "76",
                    "time": "900",
                    "uvIndex": "9",
                    "visibility": "10",
                    "visibilityMiles": "6",
                    "weatherCode": "113",
                    "weatherDesc": [{"value": "Sunny"}],
                    "weatherIconUrl": [{"value": ""}],
                    "winddir16Point": "ENE",
                    "winddirDegree": "58",
                    "windspeedKmph": "7",
                    "windspeedMiles": "4",
                },
                {
                    "DewPointC": "20",
                    "DewPointF": "68",
                    "FeelsLikeC": "28",
                    "FeelsLikeF": "82",
                    "HeatIndexC": "28",
                    "HeatIndexF": "82",
                    "WindChillC": "26",
                    "WindChillF": "79",
                    "WindGustKmph": "15",
                    "WindGustMiles": "9",
                    "chanceoffog": "0",
                    "chanceoffrost": "0",
                    "chanceofhightemp": "91",
                    "chanceofovercast": "0",
                    "chanceofrain": "0",
                    "chanceofremdry": "90",
                    "chanceofsnow": "0",
                    "chanceofsunshine": "90",
                    "chanceofthunder": "0",
                    "chanceofwindy": "0",
                    "cloudcover": "7",
                    "diffRad": "105.3",
                    "humidity": "70",
                    "precipInches": "0.0",
                    "precipMM": "0.0",
                    "pressure": "1020",
                    "pressureInches": "30",
                    "shortRad": "926.7",
                    "tempC": "26",
                    "tempF": "79",
                    "time": "1200",
                    "uvIndex": "10",
                    "visibility": "10",
                    "visibilityMiles": "6",
                    "weatherCode": "113",
                    "weatherDesc": [{"value": "Sunny"}],
                    "weatherIconUrl": [{"value": ""}],
                    "winddir16Point": "E",
                    "winddirDegree": "84",
                    "windspeedKmph": "13",
                    "windspeedMiles": "8",
                },
                {
                    "DewPointC": "20",
                    "DewPointF": "68",
                    "FeelsLikeC": "27",
                    "FeelsLikeF": "81",
                    "HeatIndexC": "27",
                    "HeatIndexF": "81",
                    "WindChillC": "25",
                    "WindChillF": "78",
                    "WindGustKmph": "26",
                    "WindGustMiles": "16",
                    "chanceoffog": "0",
                    "chanceoffrost": "0",
                    "chanceofhightemp": "75",
                    "chanceofovercast": "0",
                    "chanceofrain": "0",
                    "chanceofremdry": "86",
                    "chanceofsnow": "0",
                    "chanceofsunshine": "94",
                    "chanceofthunder": "0",
                    "chanceofwindy": "0",
                    "cloudcover": "3",
                    "diffRad": "101.4",
                    "humidity": "73",
                    "precipInches": "0.0",
                    "precipMM": "0.0",
                    "pressure": "1018",
                    "pressureInches": "30",
                    "shortRad": "912.1",
                    "tempC": "25",
                    "tempF": "78",
                    "time": "1500",
                    "uvIndex": "10",
                    "visibility": "10",
                    "visibilityMiles": "6",
                    "weatherCode": "113",
                    "weatherDesc": [{"value": "Sunny"}],
                    "weatherIconUrl": [{"value": ""}],
                    "winddir16Point": "ENE",
                    "winddirDegree": "72",
                    "windspeedKmph": "21",
                    "windspeedMiles": "13",
                },
                {
                    "DewPointC": "21",
                    "DewPointF": "69",
                    "FeelsLikeC": "26",
                    "FeelsLikeF": "79",
                    "HeatIndexC": "26",
                    "HeatIndexF": "79",
                    "WindChillC": "24",
                    "WindChillF": "75",
                    "WindGustKmph": "26",
                    "WindGustMiles": "16",
                    "chanceoffog": "0",
                    "chanceoffrost": "0",
                    "chanceofhightemp": "15",
                    "chanceofovercast": "86",
                    "chanceofrain": "71",
                    "chanceofremdry": "0",
                    "chanceofsnow": "0",
                    "chanceofsunshine": "0",
                    "chanceofthunder": "0",
                    "chanceofwindy": "0",
                    "cloudcover": "84",
                    "diffRad": "47.9",
                    "humidity": "81",
                    "precipInches": "0.0",
                    "precipMM": "0.0",
                    "pressure": "1019",
                    "pressureInches": "30",
                    "shortRad": "236.4",
                    "tempC": "24",
                    "tempF": "75",
                    "time": "1800",
                    "uvIndex": "8",
                    "visibility": "10",
                    "visibilityMiles": "6",
                    "weatherCode": "176",
                    "weatherDesc": [{"value": "Patchy rain nearby"}],
                    "weatherIconUrl": [{"value": ""}],
                    "winddir16Point": "NE",
                    "winddirDegree": "55",
                    "windspeedKmph": "18",
                    "windspeedMiles": "11",
                },
                {
                    "DewPointC": "21",
                    "DewPointF": "69",
                    "FeelsLikeC": "25",
                    "FeelsLikeF": "77",
                    "HeatIndexC": "25",
                    "HeatIndexF": "77",
                    "WindChillC": "23",
                    "WindChillF": "73",
                    "WindGustKmph": "23",
                    "WindGustMiles": "14",
                    "chanceoffog": "0",
                    "chanceoffrost": "0",
                    "chanceofhightemp": "0",
                    "chanceofovercast": "0",
                    "chanceofrain": "0",
                    "chanceofremdry": "86",
                    "chanceofsnow": "0",
                    "chanceofsunshine": "91",
                    "chanceofthunder": "0",
                    "chanceofwindy": "0",
                    "cloudcover": "12",
                    "diffRad": "20.1",
                    "humidity": "87",
                    "precipInches": "0.0",
                    "precipMM": "0.0",
                    "pressure": "1020",
                    "pressureInches": "30",
                    "shortRad": "96.3",
                    "tempC": "23",
                    "tempF": "73",
                    "time": "2100",
                    "uvIndex": "1",
                    "visibility": "10",
                    "visibilityMiles": "6",
                    "weatherCode": "113",
                    "weatherDesc": [{"value": "Clear "}],
                    "weatherIconUrl": [{"value": ""}],
                    "winddir16Point": "NE",
                    "winddirDegree": "37",
                    "windspeedKmph": "14",
                    "windspeedMiles": "9",
                },
            ],
            "maxtempC": "26",
            "maxtempF": "79",
            "mintempC": "21",
            "mintempF": "71",
            "sunHour": "12.0",
            "totalSnow_cm": "0.0",
            "uvIndex": "11",
        },
        {
            "astronomy": [
                {
                    "moon_illumination": "64",
                    "moon_phase": "Waxing Gibbous",
                    "moonrise": "03:32 PM",
                    "moonset": "12:19 AM",
                    "sunrise": "06:32 AM",
                    "sunset": "07:46 PM",
                }
            ],
            "avgtempC": "23",
            "avgtempF": "73",
            "date": "2024-02-18",
            "hourly": [
                {
                    "DewPointC": "21",
                    "DewPointF": "69",
                    "FeelsLikeC": "25",
                    "FeelsLikeF": "76",
                    "HeatIndexC": "25",
                    "HeatIndexF": "76",
                    "WindChillC": "22",
                    "WindChillF": "72",
                    "WindGustKmph": "15",
                    "WindGustMiles": "9",
                    "chanceoffog": "0",
                    "chanceoffrost": "0",
                    "chanceofhightemp": "0",
                    "chanceofovercast": "0",
                    "chanceofrain": "0",
                    "chanceofremdry": "91",
                    "chanceofsnow": "0",
                    "chanceofsunshine": "93",
                    "chanceofthunder": "0",
                    "chanceofwindy": "0",
                    "cloudcover": "19",
                    "diffRad": "0.0",
                    "humidity": "91",
                    "precipInches": "0.0",
                    "precipMM": "0.0",
                    "pressure": "1020",
                    "pressureInches": "30",
                    "shortRad": "0.0",
                    "tempC": "22",
                    "tempF": "72",
                    "time": "0",
                    "uvIndex": "1",
                    "visibility": "10",
                    "visibilityMiles": "6",
                    "weatherCode": "113",
                    "weatherDesc": [{"value": "Clear "}],
                    "weatherIconUrl": [{"value": ""}],
                    "winddir16Point": "NE",
                    "winddirDegree": "38",
                    "windspeedKmph": "9",
                    "windspeedMiles": "5",
                },
                {
                    "DewPointC": "20",
                    "DewPointF": "68",
                    "FeelsLikeC": "21",
                    "FeelsLikeF": "71",
                    "HeatIndexC": "24",
                    "HeatIndexF": "76",
                    "WindChillC": "21",
                    "WindChillF": "71",
                    "WindGustKmph": "7",
                    "WindGustMiles": "4",
                    "chanceoffog": "0",
                    "chanceoffrost": "0",
                    "chanceofhightemp": "0",
                    "chanceofovercast": "43",
                    "chanceofrain": "0",
                    "chanceofremdry": "84",
                    "chanceofsnow": "0",
                    "chanceofsunshine": "85",
                    "chanceofthunder": "0",
                    "chanceofwindy": "0",
                    "cloudcover": "28",
                    "diffRad": "0.0",
                    "humidity": "92",
                    "precipInches": "0.0",
                    "precipMM": "0.0",
                    "pressure": "1018",
                    "pressureInches": "30",
                    "shortRad": "0.0",
                    "tempC": "21",
                    "tempF": "71",
                    "time": "300",
                    "uvIndex": "1",
                    "visibility": "10",
                    "visibilityMiles": "6",
                    "weatherCode": "116",
                    "weatherDesc": [{"value": "Partly Cloudy "}],
                    "weatherIconUrl": [{"value": ""}],
                    "winddir16Point": "NNE",
                    "winddirDegree": "17",
                    "windspeedKmph": "4",
                    "windspeedMiles": "2",
                },
                {
                    "DewPointC": "20",
                    "DewPointF": "68",
                    "FeelsLikeC": "22",
                    "FeelsLikeF": "71",
                    "HeatIndexC": "24",
                    "HeatIndexF": "76",
                    "WindChillC": "22",
                    "WindChillF": "71",
                    "WindGustKmph": "5",
                    "WindGustMiles": "3",
                    "chanceoffog": "0",
                    "chanceoffrost": "0",
                    "chanceofhightemp": "0",
                    "chanceofovercast": "45",
                    "chanceofrain": "0",
                    "chanceofremdry": "83",
                    "chanceofsnow": "0",
                    "chanceofsunshine": "72",
                    "chanceofthunder": "0",
                    "chanceofwindy": "0",
                    "cloudcover": "36",
                    "diffRad": "1.3",
                    "humidity": "91",
                    "precipInches": "0.0",
                    "precipMM": "0.0",
                    "pressure": "1019",
                    "pressureInches": "30",
                    "shortRad": "2.5",
                    "tempC": "21",
                    "tempF": "71",
                    "time": "600",
                    "uvIndex": "1",
                    "visibility": "10",
                    "visibilityMiles": "6",
                    "weatherCode": "116",
                    "weatherDesc": [{"value": "Partly Cloudy "}],
                    "weatherIconUrl": [{"value": ""}],
                    "winddir16Point": "NE",
                    "winddirDegree": "37",
                    "windspeedKmph": "3",
                    "windspeedMiles": "2",
                },
                {
                    "DewPointC": "20",
                    "DewPointF": "68",
                    "FeelsLikeC": "27",
                    "FeelsLikeF": "80",
                    "HeatIndexC": "27",
                    "HeatIndexF": "80",
                    "WindChillC": "25",
                    "WindChillF": "77",
                    "WindGustKmph": "11",
                    "WindGustMiles": "7",
                    "chanceoffog": "0",
                    "chanceoffrost": "0",
                    "chanceofhightemp": "32",
                    "chanceofovercast": "0",
                    "chanceofrain": "0",
                    "chanceofremdry": "81",
                    "chanceofsnow": "0",
                    "chanceofsunshine": "88",
                    "chanceofthunder": "0",
                    "chanceofwindy": "0",
                    "cloudcover": "19",
                    "diffRad": "43.0",
                    "humidity": "73",
                    "precipInches": "0.0",
                    "precipMM": "0.0",
                    "pressure": "1020",
                    "pressureInches": "30",
                    "shortRad": "210.9",
                    "tempC": "25",
                    "tempF": "77",
                    "time": "900",
                    "uvIndex": "9",
                    "visibility": "10",
                    "visibilityMiles": "6",
                    "weatherCode": "113",
                    "weatherDesc": [{"value": "Sunny"}],
                    "weatherIconUrl": [{"value": ""}],
                    "winddir16Point": "NE",
                    "winddirDegree": "50",
                    "windspeedKmph": "9",
                    "windspeedMiles": "6",
                },
                {
                    "DewPointC": "19",
                    "DewPointF": "66",
                    "FeelsLikeC": "27",
                    "FeelsLikeF": "81",
                    "HeatIndexC": "27",
                    "HeatIndexF": "81",
                    "WindChillC": "26",
                    "WindChillF": "78",
                    "WindGustKmph": "23",
                    "WindGustMiles": "15",
                    "chanceoffog": "0",
                    "chanceoffrost": "0",
                    "chanceofhightemp": "83",
                    "chanceofovercast": "0",
                    "chanceofrain": "0",
                    "chanceofremdry": "89",
                    "chanceofsnow": "0",
                    "chanceofsunshine": "88",
                    "chanceofthunder": "0",
                    "chanceofwindy": "0",
                    "cloudcover": "11",
                    "diffRad": "94.8",
                    "humidity": "67",
                    "precipInches": "0.0",
                    "precipMM": "0.0",
                    "pressure": "1018",
                    "pressureInches": "30",
                    "shortRad": "928.5",
                    "tempC": "26",
                    "tempF": "78",
                    "time": "1200",
                    "uvIndex": "10",
                    "visibility": "10",
                    "visibilityMiles": "6",
                    "weatherCode": "113",
                    "weatherDesc": [{"value": "Sunny"}],
                    "weatherIconUrl": [{"value": ""}],
                    "winddir16Point": "ENE",
                    "winddirDegree": "64",
                    "windspeedKmph": "18",
                    "windspeedMiles": "11",
                },
                {
                    "DewPointC": "20",
                    "DewPointF": "67",
                    "FeelsLikeC": "27",
                    "FeelsLikeF": "80",
                    "HeatIndexC": "27",
                    "HeatIndexF": "80",
                    "WindChillC": "25",
                    "WindChillF": "77",
                    "WindGustKmph": "28",
                    "WindGustMiles": "17",
                    "chanceoffog": "0",
                    "chanceoffrost": "0",
                    "chanceofhightemp": "23",
                    "chanceofovercast": "87",
                    "chanceofrain": "100",
                    "chanceofremdry": "0",
                    "chanceofsnow": "0",
                    "chanceofsunshine": "0",
                    "chanceofthunder": "0",
                    "chanceofwindy": "0",
                    "cloudcover": "76",
                    "diffRad": "100.7",
                    "humidity": "72",
                    "precipInches": "0.0",
                    "precipMM": "0.1",
                    "pressure": "1017",
                    "pressureInches": "30",
                    "shortRad": "905.9",
                    "tempC": "25",
                    "tempF": "77",
                    "time": "1500",
                    "uvIndex": "8",
                    "visibility": "10",
                    "visibilityMiles": "6",
                    "weatherCode": "176",
                    "weatherDesc": [{"value": "Patchy rain nearby"}],
                    "weatherIconUrl": [{"value": ""}],
                    "winddir16Point": "NE",
                    "winddirDegree": "47",
                    "windspeedKmph": "21",
                    "windspeedMiles": "13",
                },
                {
                    "DewPointC": "18",
                    "DewPointF": "64",
                    "FeelsLikeC": "22",
                    "FeelsLikeF": "71",
                    "HeatIndexC": "24",
                    "HeatIndexF": "76",
                    "WindChillC": "22",
                    "WindChillF": "71",
                    "WindGustKmph": "8",
                    "WindGustMiles": "5",
                    "chanceoffog": "0",
                    "chanceoffrost": "0",
                    "chanceofhightemp": "0",
                    "chanceofovercast": "0",
                    "chanceofrain": "0",
                    "chanceofremdry": "84",
                    "chanceofsnow": "0",
                    "chanceofsunshine": "86",
                    "chanceofthunder": "0",
                    "chanceofwindy": "0",
                    "cloudcover": "6",
                    "diffRad": "46.0",
                    "humidity": "78",
                    "precipInches": "0.0",
                    "precipMM": "0.0",
                    "pressure": "1017",
                    "pressureInches": "30",
                    "shortRad": "78.3",
                    "tempC": "22",
                    "tempF": "71",
                    "time": "1800",
                    "uvIndex": "9",
                    "visibility": "10",
                    "visibilityMiles": "6",
                    "weatherCode": "113",
                    "weatherDesc": [{"value": "Sunny"}],
                    "weatherIconUrl": [{"value": ""}],
                    "winddir16Point": "SE",
                    "winddirDegree": "134",
                    "windspeedKmph": "4",
                    "windspeedMiles": "3",
                },
                {
                    "DewPointC": "18",
                    "DewPointF": "65",
                    "FeelsLikeC": "22",
                    "FeelsLikeF": "71",
                    "HeatIndexC": "24",
                    "HeatIndexF": "76",
                    "WindChillC": "22",
                    "WindChillF": "71",
                    "WindGustKmph": "6",
                    "WindGustMiles": "4",
                    "chanceoffog": "0",
                    "chanceoffrost": "0",
                    "chanceofhightemp": "0",
                    "chanceofovercast": "0",
                    "chanceofrain": "0",
                    "chanceofremdry": "92",
                    "chanceofsnow": "0",
                    "chanceofsunshine": "90",
                    "chanceofthunder": "1",
                    "chanceofwindy": "0",
                    "cloudcover": "8",
                    "diffRad": "20.8",
                    "humidity": "80",
                    "precipInches": "0.0",
                    "precipMM": "0.0",
                    "pressure": "1018",
                    "pressureInches": "30",
                    "shortRad": "36.6",
                    "tempC": "22",
                    "tempF": "71",
                    "time": "2100",
                    "uvIndex": "1",
                    "visibility": "10",
                    "visibilityMiles": "6",
                    "weatherCode": "113",
                    "weatherDesc": [{"value": "Clear "}],
                    "weatherIconUrl": [{"value": ""}],
                    "winddir16Point": "NNE",
                    "winddirDegree": "21",
                    "windspeedKmph": "3",
                    "windspeedMiles": "2",
                },
            ],
            "maxtempC": "26",
            "maxtempF": "79",
            "mintempC": "21",
            "mintempF": "70",
            "sunHour": "12.0",
            "totalSnow_cm": "0.0",
            "uvIndex": "11",
        },
        {
            "astronomy": [
                {
                    "moon_illumination": "74",
                    "moon_phase": "Waxing Gibbous",
                    "moonrise": "04:31 PM",
                    "moonset": "01:07 AM",
                    "sunrise": "06:33 AM",
                    "sunset": "07:45 PM",
                }
            ],
            "avgtempC": "22",
            "avgtempF": "71",
            "date": "2024-02-19",
            "hourly": [
                {
                    "DewPointC": "20",
                    "DewPointF": "68",
                    "FeelsLikeC": "22",
                    "FeelsLikeF": "71",
                    "HeatIndexC": "24",
                    "HeatIndexF": "76",
                    "WindChillC": "22",
                    "WindChillF": "71",
                    "WindGustKmph": "9",
                    "WindGustMiles": "5",
                    "chanceoffog": "0",
                    "chanceoffrost": "0",
                    "chanceofhightemp": "0",
                    "chanceofovercast": "89",
                    "chanceofrain": "70",
                    "chanceofremdry": "0",
                    "chanceofsnow": "0",
                    "chanceofsunshine": "0",
                    "chanceofthunder": "1",
                    "chanceofwindy": "0",
                    "cloudcover": "51",
                    "diffRad": "0.0",
                    "humidity": "91",
                    "precipInches": "0.0",
                    "precipMM": "0.0",
                    "pressure": "1018",
                    "pressureInches": "30",
                    "shortRad": "0.0",
                    "tempC": "22",
                    "tempF": "71",
                    "time": "0",
                    "uvIndex": "1",
                    "visibility": "10",
                    "visibilityMiles": "6",
                    "weatherCode": "176",
                    "weatherDesc": [{"value": "Patchy rain nearby"}],
                    "weatherIconUrl": [{"value": ""}],
                    "winddir16Point": "NE",
                    "winddirDegree": "52",
                    "windspeedKmph": "5",
                    "windspeedMiles": "3",
                },
                {
                    "DewPointC": "20",
                    "DewPointF": "68",
                    "FeelsLikeC": "21",
                    "FeelsLikeF": "70",
                    "HeatIndexC": "24",
                    "HeatIndexF": "76",
                    "WindChillC": "21",
                    "WindChillF": "70",
                    "WindGustKmph": "5",
                    "WindGustMiles": "3",
                    "chanceoffog": "0",
                    "chanceoffrost": "0",
                    "chanceofhightemp": "0",
                    "chanceofovercast": "91",
                    "chanceofrain": "69",
                    "chanceofremdry": "0",
                    "chanceofsnow": "0",
                    "chanceofsunshine": "0",
                    "chanceofthunder": "0",
                    "chanceofwindy": "0",
                    "cloudcover": "52",
                    "diffRad": "0.0",
                    "humidity": "91",
                    "precipInches": "0.0",
                    "precipMM": "0.0",
                    "pressure": "1017",
                    "pressureInches": "30",
                    "shortRad": "0.0",
                    "tempC": "21",
                    "tempF": "70",
                    "time": "300",
                    "uvIndex": "1",
                    "visibility": "10",
                    "visibilityMiles": "6",
                    "weatherCode": "176",
                    "weatherDesc": [{"value": "Patchy rain nearby"}],
                    "weatherIconUrl": [{"value": ""}],
                    "winddir16Point": "N",
                    "winddirDegree": "353",
                    "windspeedKmph": "3",
                    "windspeedMiles": "2",
                },
                {
                    "DewPointC": "19",
                    "DewPointF": "67",
                    "FeelsLikeC": "21",
                    "FeelsLikeF": "70",
                    "HeatIndexC": "21",
                    "HeatIndexF": "70",
                    "WindChillC": "21",
                    "WindChillF": "70",
                    "WindGustKmph": "10",
                    "WindGustMiles": "6",
                    "chanceoffog": "0",
                    "chanceoffrost": "0",
                    "chanceofhightemp": "0",
                    "chanceofovercast": "45",
                    "chanceofrain": "0",
                    "chanceofremdry": "94",
                    "chanceofsnow": "0",
                    "chanceofsunshine": "88",
                    "chanceofthunder": "2",
                    "chanceofwindy": "0",
                    "cloudcover": "55",
                    "diffRad": "1.5",
                    "humidity": "91",
                    "precipInches": "0.0",
                    "precipMM": "0.0",
                    "pressure": "1018",
                    "pressureInches": "30",
                    "shortRad": "3.0",
                    "tempC": "21",
                    "tempF": "70",
                    "time": "600",
                    "uvIndex": "1",
                    "visibility": "10",
                    "visibilityMiles": "6",
                    "weatherCode": "116",
                    "weatherDesc": [{"value": "Partly Cloudy "}],
                    "weatherIconUrl": [{"value": ""}],
                    "winddir16Point": "S",
                    "winddirDegree": "174",
                    "windspeedKmph": "6",
                    "windspeedMiles": "4",
                },
                {
                    "DewPointC": "20",
                    "DewPointF": "67",
                    "FeelsLikeC": "26",
                    "FeelsLikeF": "78",
                    "HeatIndexC": "26",
                    "HeatIndexF": "78",
                    "WindChillC": "24",
                    "WindChillF": "75",
                    "WindGustKmph": "6",
                    "WindGustMiles": "4",
                    "chanceoffog": "0",
                    "chanceoffrost": "0",
                    "chanceofhightemp": "10",
                    "chanceofovercast": "90",
                    "chanceofrain": "100",
                    "chanceofremdry": "0",
                    "chanceofsnow": "0",
                    "chanceofsunshine": "0",
                    "chanceofthunder": "4",
                    "chanceofwindy": "0",
                    "cloudcover": "50",
                    "diffRad": "75.0",
                    "humidity": "77",
                    "precipInches": "0.0",
                    "precipMM": "0.1",
                    "pressure": "1019",
                    "pressureInches": "30",
                    "shortRad": "171.2",
                    "tempC": "24",
                    "tempF": "75",
                    "time": "900",
                    "uvIndex": "8",
                    "visibility": "10",
                    "visibilityMiles": "6",
                    "weatherCode": "176",
                    "weatherDesc": [{"value": "Patchy rain nearby"}],
                    "weatherIconUrl": [{"value": ""}],
                    "winddir16Point": "ESE",
                    "winddirDegree": "116",
                    "windspeedKmph": "5",
                    "windspeedMiles": "3",
                },
                {
                    "DewPointC": "19",
                    "DewPointF": "67",
                    "FeelsLikeC": "27",
                    "FeelsLikeF": "80",
                    "HeatIndexC": "27",
                    "HeatIndexF": "80",
                    "WindChillC": "25",
                    "WindChillF": "77",
                    "WindGustKmph": "20",
                    "WindGustMiles": "12",
                    "chanceoffog": "0",
                    "chanceoffrost": "0",
                    "chanceofhightemp": "15",
                    "chanceofovercast": "84",
                    "chanceofrain": "0",
                    "chanceofremdry": "91",
                    "chanceofsnow": "0",
                    "chanceofsunshine": "7",
                    "chanceofthunder": "17",
                    "chanceofwindy": "0",
                    "cloudcover": "48",
                    "diffRad": "335.6",
                    "humidity": "71",
                    "precipInches": "0.0",
                    "precipMM": "0.0",
                    "pressure": "1017",
                    "pressureInches": "30",
                    "shortRad": "753.3",
                    "tempC": "25",
                    "tempF": "77",
                    "time": "1200",
                    "uvIndex": "8",
                    "visibility": "9",
                    "visibilityMiles": "5",
                    "weatherCode": "200",
                    "weatherDesc": [{"value": "Thundery outbreaks in nearby"}],
                    "weatherIconUrl": [{"value": ""}],
                    "winddir16Point": "E",
                    "winddirDegree": "83",
                    "windspeedKmph": "16",
                    "windspeedMiles": "10",
                },
                {
                    "DewPointC": "19",
                    "DewPointF": "67",
                    "FeelsLikeC": "26",
                    "FeelsLikeF": "79",
                    "HeatIndexC": "26",
                    "HeatIndexF": "79",
                    "WindChillC": "24",
                    "WindChillF": "76",
                    "WindGustKmph": "25",
                    "WindGustMiles": "15",
                    "chanceoffog": "0",
                    "chanceoffrost": "0",
                    "chanceofhightemp": "15",
                    "chanceofovercast": "0",
                    "chanceofrain": "0",
                    "chanceofremdry": "89",
                    "chanceofsnow": "0",
                    "chanceofsunshine": "93",
                    "chanceofthunder": "17",
                    "chanceofwindy": "0",
                    "cloudcover": "20",
                    "diffRad": "341.3",
                    "humidity": "72",
                    "precipInches": "0.0",
                    "precipMM": "0.0",
                    "pressure": "1016",
                    "pressureInches": "30",
                    "shortRad": "706.2",
                    "tempC": "24",
                    "tempF": "76",
                    "time": "1500",
                    "uvIndex": "9",
                    "visibility": "10",
                    "visibilityMiles": "6",
                    "weatherCode": "113",
                    "weatherDesc": [{"value": "Sunny"}],
                    "weatherIconUrl": [{"value": ""}],
                    "winddir16Point": "E",
                    "winddirDegree": "81",
                    "windspeedKmph": "19",
                    "windspeedMiles": "12",
                },
                {
                    "DewPointC": "19",
                    "DewPointF": "67",
                    "FeelsLikeC": "25",
                    "FeelsLikeF": "77",
                    "HeatIndexC": "25",
                    "HeatIndexF": "77",
                    "WindChillC": "23",
                    "WindChillF": "73",
                    "WindGustKmph": "20",
                    "WindGustMiles": "12",
                    "chanceoffog": "0",
                    "chanceoffrost": "0",
                    "chanceofhightemp": "0",
                    "chanceofovercast": "80",
                    "chanceofrain": "100",
                    "chanceofremdry": "0",
                    "chanceofsnow": "0",
                    "chanceofsunshine": "0",
                    "chanceofthunder": "4",
                    "chanceofwindy": "0",
                    "cloudcover": "88",
                    "diffRad": "102.2",
                    "humidity": "80",
                    "precipInches": "0.0",
                    "precipMM": "0.1",
                    "pressure": "1016",
                    "pressureInches": "30",
                    "shortRad": "191.4",
                    "tempC": "23",
                    "tempF": "73",
                    "time": "1800",
                    "uvIndex": "8",
                    "visibility": "10",
                    "visibilityMiles": "6",
                    "weatherCode": "176",
                    "weatherDesc": [{"value": "Patchy rain nearby"}],
                    "weatherIconUrl": [{"value": ""}],
                    "winddir16Point": "E",
                    "winddirDegree": "92",
                    "windspeedKmph": "13",
                    "windspeedMiles": "8",
                },
                {
                    "DewPointC": "18",
                    "DewPointF": "64",
                    "FeelsLikeC": "20",
                    "FeelsLikeF": "69",
                    "HeatIndexC": "20",
                    "HeatIndexF": "69",
                    "WindChillC": "20",
                    "WindChillF": "69",
                    "WindGustKmph": "19",
                    "WindGustMiles": "12",
                    "chanceoffog": "0",
                    "chanceoffrost": "0",
                    "chanceofhightemp": "0",
                    "chanceofovercast": "85",
                    "chanceofrain": "100",
                    "chanceofremdry": "0",
                    "chanceofsnow": "0",
                    "chanceofsunshine": "0",
                    "chanceofthunder": "0",
                    "chanceofwindy": "0",
                    "cloudcover": "83",
                    "diffRad": "41.9",
                    "humidity": "85",
                    "precipInches": "0.0",
                    "precipMM": "0.3",
                    "pressure": "1018",
                    "pressureInches": "30",
                    "shortRad": "78.5",
                    "tempC": "20",
                    "tempF": "69",
                    "time": "2100",
                    "uvIndex": "1",
                    "visibility": "9",
                    "visibilityMiles": "5",
                    "weatherCode": "176",
                    "weatherDesc": [{"value": "Patchy rain nearby"}],
                    "weatherIconUrl": [{"value": ""}],
                    "winddir16Point": "NNW",
                    "winddirDegree": "328",
                    "windspeedKmph": "12",
                    "windspeedMiles": "7",
                },
            ],
            "maxtempC": "24",
            "maxtempF": "75",
            "mintempC": "20",
            "mintempF": "69",
            "sunHour": "10.8",
            "totalSnow_cm": "0.0",
            "uvIndex": "9",
        },
    ],
}
